# Generated by Django 3.2.8 on 2022-07-26 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(null=True, verbose_name='Descripcion')),
                ('status', models.CharField(max_length=20, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Vacant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_complete', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('experience_start_date', models.CharField(max_length=20, verbose_name='Fecha Inicio Experiencia')),
                ('city', models.CharField(max_length=150, verbose_name='Ciudad')),
                ('email', models.EmailField(max_length=250, verbose_name='Correo Electronico')),
                ('dni', models.CharField(max_length=30, verbose_name='Identidad')),
                ('status', models.CharField(max_length=25, verbose_name='Estado')),
                ('country', models.CharField(max_length=50, verbose_name='Pais')),
                ('modality', models.CharField(max_length=50, verbose_name='Modalidad')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job_position')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('vacant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vacant')),
            ],
        ),
    ]
